[molecules]
molecule = 'CO'
n_molecules = 4
compresion_factor = 1  # How close molecules will be inside the CNT
add_tilt = true
tilt_factor = 15    # max randomly molecular tilt around either x or y

[cnt]
# n,m nanotube vectors
cnt_n = 8
cnt_m = 0
cnt_l = 2    # Repetition units of a single CNT
cnt_gap = 4  # Distance betwen CNTs (Ang)

[config]
# Random things
random_seed = false
seed = 43  # If not random_seed, use this instead

# ---------------------------
# Calculation parameters
# ---------------------------
[calculator]

  [calculator.qe]
    calculation = 'scf'
    ecutwfc = 30     # plane-wave wave-function cutoff
    #ecutwfc = 45     # plane-wave wave-function cutoff
    ecutrho = 180    # density wave-function cutoff,
    conv_thr = 1e-6  # DFT self-consistency convergence
    pseudo_dir = "/home/david/pseudos/qe/SSSP_1.1.2_PBE_precision/"
    vdw_corr = "xdm"
    occupations = "smearing"   # Add smearing
    smearing = "cold"  # smearing kind
    degauss = 0.02     # smearing amount
    tprnfor = true     # Print forces
    tstress = true     # Print stress tensor
    kpts = [1,1,2]

    [calculator.qe.pseudos]
      C = 'C.pbe-n-kjpaw_psl.1.0.0.UPF'
      O = 'O.pbe-n-kjpaw_psl.0.1.UPF'
