# ----------------------------
# Building geometry parameters
# ----------------------------
[structures]
n_structures = 5  # Total number of random geoemtries to be generated

[molecules]
molecule = 'CO2'
n_molecules = 4
compresion_factor = 1.0  # How close molecules will be inside the CNT

# TODO: Add posibility for totally random rotation?
#
# Axis order in which rotations will be performed, the same axis can be given several times, so several rotations will be performd
# Non mandatory. Default is ['x', 'y', 'z']
# rot_axis = ['y', 'x', 'z', 'y']
rot_axis = ['x', 'y', 'z']

# Rotations for each molecule (in degrees) 
# (Non mandatory)
rot_x = 90
rot_y = {'min' = 80, 'max' = 100}
rot_z = {'min' = 0, 'max' = 360}

[cnt]
# n,m nanotube vectors
cnt_n = 8
cnt_m = 0
cnt_l = 2    # Repetition units of a single CNT
cnt_gap = 4  # Distance betwen CNTs (Ang)

# ---------------------------
# Calculation parameters
# ---------------------------
[calculator]
calculator = 'qe'  # Use Quantum Espresso to calculate enrgies/forces
calculate_energies = false
calculate_forces = true

  # Set the calculator parameters
  [calculator.qe]
    calculation = 'scf'
    #ecutwfc = 30     # plane-wave wave-function cutoff
    ecutwfc = 45     # plane-wave wave-function cutoff
    ecutrho = 180    # density wave-function cutoff,
    conv_thr = 1e-6  # DFT self-consistency convergence
    pseudo_dir = "/home/david/pseudos/qe/SSSP_1.1.2_PBE_precision/"
    vdw_corr = "xdm"
    occupations = "smearing"   # Add smearing
    smearing = "cold"  # smearing kind
    degauss = 0.02     # smearing amount
    tprnfor = true     # Print forces
    tstress = true     # Print stress tensor
    kpts = [1,1,2]

    [calculator.qe.pseudos]
      C = 'C.pbe-n-kjpaw_psl.1.0.0.UPF'
      O = 'O.pbe-n-kjpaw_psl.0.1.UPF'

# ---------------------------
# Visualization parameters
# ---------------------------
[visualize]
# You wanna see the geometries?
visualize = true
# repeat = [1,1,3]

# ---------------------------
# General configuration stuff
# ---------------------------
[config]
# Random things
random_seed = true
seed = 42  # If random_seed is false, use this seed instead

# Paths and files
folder_prefix = 'cnt'
logfile = 'test.log'
# outdir = './'

# Parallelization
nproc = 4   # Number of cores to run qe as: mpiexec -np nproc ...
