[build-system]

requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"


[tool.setuptools]

package-dir = {"" = "src"}


[tool.setuptools.packages.find]

where = ["src"]


[project]

name = "traincraft"
version = "0.0.1"


[project.scripts]

traincraft = "traincraft.__main__:main"
