# Reference input file in TOML format
title = 'Input file example for reference'

[structures]
n_structures = 5  # Total number of initial random geometries to be generated

[molecules]
molecule = 'CO2'
n_molecules = 4
tolerance = 2   # Minimum intermolecular distance for Packmol to distribute the molecules

[cnt]
# n,m nanotube vectors
cnt_n    = 8
cnt_m    = 0
cnt_l    = 2         # Repetition units of a single CNT
cnt_bond = 1.45      # Bond lenght in the CNT
cnt_gap  = 4         # Distance betwen CNTs (Ang)

[preoptimize]
fmax = 5             # Max force in atoms

# [sampling]
# method = 'md'           # 'md'(*) | 'rattle'; How to sample geometries
# calculator = 'tblite'   # 'tblite'(*) | 'xtb' | 'ani'; Calculator to use for the sampling method

# ---------------------------
# Calculation parameters
# ---------------------------
# Quantum Mechanical Calculator
[calculator]
calculator = 'qe'          # Use Quantum Espresso as calculator to calculate  DFT energies/forces
calculate_forces = false   # If true: DFT forces will be calculated
write_input_file = true    # Writes the input file regardless forces being calculated
