# Work input file in TOML format
title = 'Input file example. Use as a reference'

# ----------------------------
# Building geometry parameters
# ----------------------------
[structures]
n_structures = 10  # Total number of random geoemtries to be generated

[molecules]
molecule = 'CO2'
n_molecules = 6
compresion_factor = 1.0  # How close molecules will be inside the CNT

# TODO: Add posibility for totally random rotation?
#
# Axis order in which rotations will be performed, the same axis can be given
# several times, so several rotations will be performd
# Non mandatory. Default is ['x', 'y', 'z']
# rot_axis = ['y', 'x', 'z', 'y']
rot_axis = ['x', 'z', 'y']

# Rotations for each molecule (in degrees) 
# (Non mandatory)
rot_x = 90
rot_y = {'min' = -25.0, 'max' = 25.0}
rot_z = {'min' = 0, 'max' = 360}

[cnt]
# n,m nanotube vectors
cnt_n = 8
cnt_m = 0
cnt_l = 2    # Repetition units of a single CNT
cnt_bond = 1.42  # Bond lenght in the CNT
cnt_gap = 4  # Distance betwen CNTs (Ang)
constraints = 'all'

# ---------------------------
# Calculation parameters
# ---------------------------
[calculator]
calculator = 'qe'  # Use Quantum Espresso to calculate enrgies/forces
calculate_energies = false
calculate_forces = false

  # Set the calculator parameters
  [calculator.qe]
    # calculation = 'scf'
    calculation = 'relax'
    # ecutwfc = 30         # plane-wave wave-function cutoff
    ecutwfc = 45          # plane-wave wave-function cutoff
    ecutrho = 180         # density wave-function cutoff,
    conv_thr = 1e-8       # DFT self-consistency convergence
    forc_conv_thr = 1e-3  # Force convergence threshold
    etot_conv_thr = 1e-5  # Total energy convergence threshold
    nstep = 100           # Total ionic steps
    pseudo_dir = "/home/david/pseudos/qe/SSSP_1.1.2_PBE_precision/"
    vdw_corr = "xdm"
    occupations = "smearing"   # Add smearing
    smearing = "cold"  # smearing kind
    degauss = 0.02     # smearing amount
    tprnfor = true     # Print forces
    tstress = true     # Print stress tensor
    kpts = [1,1,2]

    [calculator.qe.pseudos]
      C = 'C.pbe-n-kjpaw_psl.1.0.0.UPF'
      O = 'O.pbe-n-kjpaw_psl.0.1.UPF'

# ---------------------------
# Visualization parameters
# ---------------------------
[visualize]
# You wanna see the geometries?
visualize = true
# repeat = [1,1,3]

# ---------------------------
# General configuration stuff
# ---------------------------
[config]
# Random things
random_seed = true
# seed = 42  # If random_seed is false, use this seed instead

# Paths and files
folder_prefix = 'cnt'
logfile = 'logfile.log'
# outdir = './'

# Parallelization (Experimental!)
# nproc = 4   # Number of MPI processes to run qe as: mpiexec -np nproc ...
