# Work input file in TOML format
title = 'Input file example for reference'

# ----------------------------
# Building geometry parameters
# ----------------------------

# geom_generation = 'manual'   # 'manual': Manual geometry generation
                               # 'auto'  : Packmol will be used

[structures]
n_structures = 5  # Total number of initial random geometries to be generated

[molecules]
molecule = 'CO2'
n_molecules = 3
tolerance = 2   # Minimum intermolecular distance for Packmol to distribute the molecules

# compresion_factor = 1.0  # How close molecules will be inside the CNT

# Axis order in which rotations will be performed, the same axis can be given
# several times, so several rotations will be performed
# Default is ['x', 'y', 'z']
# rot_axis = ['y', 'x', 'z', 'y']
rot_axis = ['x', 'z', 'y']

# Rotations for each molecule (in degrees)
rot_x = 90
rot_y = {'min' = -25.0, 'max' = 25.0}
rot_z = {'min' = 0, 'max' = 360}

[cnt]
# n,m nanotube vectors
cnt_n    = 8
cnt_m    = 0
cnt_l    = 2         # Repetition units of a single CNT
cnt_bond = 1.45      # Bond lenght in the CNT
cnt_gap  = 4         # Distance betwen CNTs (Ang)
# constraints = 'all'  # Not used

[sampling]
method = 'md'           #  How to sample geometries for DFT calculations
                        #   'md' | 'rattle'
calculator = 'tblite'   # Calculator to use for the sampling method

[sampling.md]
  sampling_interval = 20
  temperature = 500
  md_steps = 1000

[sampling.rattle]
  rattle_structures = 10   # how many rattle geoetries at each structure
  rattle_std = 0.12


# ---------------------------
# Calculation parameters
# ---------------------------
[calculator]
calculator = 'qe'          # Use Quantum Espresso to calculate enrgies/forces
calculate_forces = false   # If true: DFT forces will be calculated from MD sampled geometries

  # Set the calculator parameters
  [calculator.qe]
    calculation = 'scf'
    # ecutwfc = 30        # plane-wave wave-function cutoff
    ecutwfc = 50          # plane-wave wave-function cutoff
    ecutrho = 600         # density wave-function cutoff
    conv_thr = 1e-8       # DFT self-consistency convergence
    forc_conv_thr = 1e-3  # Force convergence threshold
    etot_conv_thr = 1e-5  # Total energy convergence threshold
    nstep = 100           # Total ionic steps
    pseudo_dir = "/home/david/pseudos/qe/SSSP_1.1.2_PBE_precision/"
    vdw_corr = "xdm"
    occupations = "smearing"   # Add smearing
    smearing = "cold"  # smearing kind
    degauss = 0.02     # smearing amount
    tprnfor = true     # Print forces
    tstress = true     # Print stress tensor
    kpts = [1,1,2]

    [calculator.qe.pseudos]
      C = 'C.pbe-n-kjpaw_psl.1.0.0.UPF'
      O = 'O.pbe-n-kjpaw_psl.0.1.UPF'


# ---------------------------
# Visualization parameters
# ---------------------------
[visualize]
# You wanna see the geometries?
visualize = false
# repeat = [1,1,3]

# ---------------------------
# General configuration stuff
# ---------------------------
[config]
# Random things
random_seed = true
# seed = 42  # If random_seed is false, use this seed instead

# Paths and files
folder_prefix = 'dataset'
# logfile = 'logfile.log'
# outdir = './'

# Parallelization (Experimental!)
# nproc = 4   # Number of MPI processes to run qe as: mpiexec -np nproc ...
